# Generated by Django 5.0.4 on 2024-04-08 06:13

import core.utils.db_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YTDataV3Credentials",
            fields=[
                ("create_time", models.DateField(auto_now_add=True)),
                ("update_time", models.DateField(auto_now=True)),
                ("encrypted_text", core.utils.db_utils.EncryptedTextField()),
                ("encrypted_hash", models.CharField(blank=True, max_length=256)),
                ("project_id", models.CharField(primary_key=True, serialize=False)),
                ("project_name", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="YTMetadata",
            fields=[
                ("create_time", models.DateField(auto_now_add=True)),
                ("update_time", models.DateField(auto_now=True)),
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("title", models.CharField()),
                ("description", models.TextField()),
                ("published_at", models.DateTimeField()),
                ("thumbnail_url", models.URLField()),
                ("channel_name", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
